In [1]:
import pandas as pd

# Function to import data from a CSV file
def import_data(file_path):
    try:
        data = pd.read_csv('data set.csv')
        return data
    except Exception as e:
        print(f"Error: {e}")
        return None

# Function to export data to a CSV file
def export_data(data, output_file_path):
    try:
        data.to_csv(output_file_path, index=False)
        print(f"Data exported successfully to {output_file_path}")
    except Exception as e:
        print(f"Error: {e}")

# Function to display dataset details
def display_details(data):
    if data is not None:
        print("Dataset Information:")
        print(f"Number of Rows: {data.shape[0]}")
        print(f"Number of Columns: {data.shape[1]}")
        print("\nFirst Five Rows:")
        print(data.head())
        print(f"\nSize of the Dataset (Total Elements): {data.size}")
        print("\nNumber of Missing Values in Each Column:")
        print(data.isnull().sum())

        print("\nSummary Statistics for Numerical Columns:")
        print(data.describe())

        numerical_cols = data.select_dtypes(include=['number'])
        if not numerical_cols.empty:
            print(f"\nSum of Numerical Columns:\n{numerical_cols.sum()}")
            print(f"\nMean of Numerical Columns:\n{numerical_cols.mean()}")
            print(f"\nMin Values of Numerical Columns:\n{numerical_cols.min()}")
            print(f"\nMax Values of Numerical Columns:\n{numerical_cols.max()}")
        else:
            print("\nNo numerical columns found.")
    else:
        print("No data to display.")

# Example usage
file_path = 'your_dataset.csv'  # Replace with your file path
output_file_path = 'exported_data.csv'

# Importing the data
data = import_data(file_path)

# Displaying dataset details
display_details(data)

# Exporting the data to a new CSV file
export_data(data, output_file_path)

Dataset Information:
Number of Rows: 1201
Number of Columns: 14

First Five Rows:
  Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
0  SSSQ.SFMN1111CA  2004.06    1248.356         NaN      F  dollars
1  SSSQ.SFMN1111CA  2004.09    1220.571         NaN      F  dollars
2  SSSQ.SFMN1111CA  2004.12    1263.820         NaN      F  dollars
3  SSSQ.SFMN1111CA  2005.03    1146.156         NaN      F  dollars
4  SSSQ.SFMN1111CA  2005.06    1382.692         NaN      F  dollars

   Magnitude                                    Subject  \
0        6.0  Selected Services Survey (ANZSIC06) - SSS
1        6.0  Selected Services Survey (ANZSIC06) - SSS
2        6.0  Selected Services Survey (ANZSIC06) - SSS
3        6.0  Selected Services Survey (ANZSIC06) - SSS
4        6.0  Selected Services Survey (ANZSIC06) - SSS

                                             Group  \
0  Industry sales - Subannual Financial Collection
1  Industry sales - Subannual Financial Collection
2  Industry sales - Subannual Financial Collection
3  Industry sales - Subannual Financial Collection
4  Industry sales - Subannual Financial Collection

                                      Series_title_1  \
0  Scientific, Architectural and Engineering Serv...
1  Scientific, Architectural and Engineering Serv...
2  Scientific, Architectural and Engineering Serv...
3  Scientific, Architectural and Engineering Serv...
4  Scientific, Architectural and Engineering Serv...

             Series_title_2  Series_title_3 Series_title_4  Series_title_5
0  Sales (operating income)  Current prices         Actual             NaN
1  Sales (operating income)  Current prices         Actual             NaN
2  Sales (operating income)  Current prices         Actual             NaN
3  Sales (operating income)  Current prices         Actual             NaN
4  Sales (operating income)  Current prices         Actual             NaN

Size of the Dataset (Total Elements): 16814

Number of Missing Values in Each Column:
Series_reference     980
Period               980
Data_value           980
Suppressed          1201
STATUS               980
UNITS                980
Magnitude            980
Subject              980
Group                980
Series_title_1       980
Series_title_2       980
Series_title_3       980
Series_title_4       980
Series_title_5      1201
dtype: int64

Summary Statistics for Numerical Columns:
            Period   Data_value  Suppressed  Magnitude  Series_title_5
count   221.000000   221.000000         0.0      221.0             0.0
mean   2013.215339  2125.479647         NaN        6.0             NaN
std       5.621316   777.268402         NaN        0.0             NaN
min    2004.060000  1146.156000         NaN        6.0             NaN
25%    2008.120000  1533.197000         NaN        6.0             NaN
50%    2013.060000  1838.649000         NaN        6.0             NaN
75%    2018.030000  2608.092000         NaN        6.0             NaN
max    2024.060000  4215.970000         NaN        6.0             NaN

Sum of Numerical Columns:
Period            444920.590
Data_value        469731.002
Suppressed             0.000
Magnitude           1326.000
Series_title_5         0.000
dtype: float64

Mean of Numerical Columns:
Period            2013.215339
Data_value        2125.479647
Suppressed                NaN
Magnitude            6.000000
Series_title_5            NaN
dtype: float64

Min Values of Numerical Columns:
Period            2004.060
Data_value        1146.156
Suppressed             NaN
Magnitude            6.000
Series_title_5         NaN
dtype: float64

Max Values of Numerical Columns:
Period            2024.06
Data_value        4215.97
Suppressed            NaN
Magnitude            6.00
Series_title_5        NaN
dtype: float64
Data exported successfully to exported_data.csv